version: '3'
services:
  driveback:
    image: nodeimage
    container_name: nodeserver
    build: .
    restart: always
    ports:
    - "3000:3000"
    links:
     - mongodb
    volumes:
     - .:/usr/src/app
      # Anonymous volume:
     - /usr/src/app/node_modules
   
    environment:
    - HOST:0.0.0.0
    - PORT:3000
  mongodb: 
    container_name: mongodatabase
    image: mongo:4.4.6
    ports: 
    - "27017:27017"
    restart: always
    logging:
      driver: "none"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongodb://root:12345@mongodb:27017/

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
