version: '3'
services:
  driveback:
    image: nodeimage
    container_name: nodeserver
    build: ./
    restart: always
    ports:
    - "3000:3000"
    links:
     - mongodb
    volumes:
     - .:/usr/srv/app
   
    environment:
    - HOST:0.0.0.0
    - PORT:3000
  mongodb: 
    container_name: mongodatabase
    image: mongo:4.4.6
    ports: 
    - "27017:27017"
    logging:
     driver: none